name: continuous integration

on:
    pull_request:
    push:
        branches: ['develop', 'main']

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: pnpm i

            - name: Build
              run: pnpm run build

            - name: Test
              run: pnpm test

            - name: Linter and Format
              run: npm run linter-check
