name: vercel preview deploy

on:
  push:
    branches:
      - main

jobs:
  preview:
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: preview
      production: false
    secrets: inherit
