name: vercel deploy reusable

on:
  workflow_call:
    inputs:
      environment:
        description: Vercel environment to deploy
        required: true
        type: string
      production:
        description: Whether to deploy production artifacts
        required: true
        type: boolean

env:
  CLIENT_DIR: apps/client-pixi
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

defaults:
  run:
    working-directory: apps/client-pixi

jobs:
  deploy:
    name: Deploy to Vercel (${{ inputs.environment }})
    runs-on: ubuntu-latest
    concurrency:
      group: vercel-${{ inputs.environment }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-client
        with:
          working-directory: ${{ env.CLIENT_DIR }}

      - name: Install Vercel
        run: pnpm add -g vercel@canary

      - name: Generate assets
        run: pnpm run generate-assets

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build ${{ inputs.production && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to Vercel
        run: vercel deploy --prebuilt ${{ inputs.production && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}
