name: vercel production deploy

on:
  push:
    branches:
      - main

jobs:
  production:
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: production
      production: true
    secrets: inherit
