name: vercel deploy reusable

on:
  workflow_call:
    inputs:
      environment:
        description: Vercel environment to deploy
        required: true
        type: string
      production:
        description: Whether to deploy production artifacts
        required: true
        type: boolean

env:
  CLIENT_DIR: apps/client
  GODOT_VERSION: 4.7.0
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy to Vercel (${{ inputs.environment }})
    runs-on: ubuntu-latest
    concurrency:
      group: vercel-${{ inputs.environment }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - uses: chickensoft-games/setup-godot@v2
        with:
          version: ${{ env.GODOT_VERSION }}
          use-dotnet: false
          include-templates: true

      - name: Install Vercel
        run: npm install --global vercel@canary

      - name: Import Godot project
        run: godot --headless --path "${{ env.CLIENT_DIR }}" --import

      - name: Export Web build
        run: |
          rm -rf "${{ env.CLIENT_DIR }}/export/web"
          godot --headless --path "${{ env.CLIENT_DIR }}" --export-release "Web" "export/web/index.html"

      - name: Pull Vercel environment information
        working-directory: ${{ env.CLIENT_DIR }}
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to Vercel
        working-directory: ${{ env.CLIENT_DIR }}
        run: vercel deploy --yes ${{ inputs.production && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}
